version: '3'

services:
  web:
    build: ./member2
    ports:
      - "8080:5000"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - webapp
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "3306:27017"
    volumes:
      - ./db_data:/var/lib/webapp
    networks:
      - webapp

networks:
  mynetwork:
    driver: bridge
